# Generated by Django 6.0.6 on 2026-06-25 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('bank_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('reporting_year', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('processed', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_text', models.TextField()),
                ('recommendations', models.JSONField(default=list)),
                ('avoid', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk_analysis.riskanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
