import logging

from django.http import Http404
from rest_framework import (
    generics,
    status,
)
from rest_framework.permissions import (
    IsAuthenticated,
)
from rest_framework.response import Response
from rest_framework.views import APIView

from payloads.services import (
    PayloadStorageError,
    resolve_payload_directory,
)

from . import (
    llm,
    services,
    validators,
)
from .models import (
    AssessmentResult,
    RiskAnalysis,
)
from .serializers import (
    AssessmentResultSerializer,
    RiskAnalysisDetailSerializer,
    RiskAnalysisListSerializer,
    StartRiskAnalysisSerializer,
)


logger = logging.getLogger(__name__)


def _analysis_queryset_for_user(user):
    queryset = (
        RiskAnalysis.objects
        .select_related(
            "uploaded_by",
            "payload_manifest",
            "payload_manifest__bank",
        )
    )

    if (
        getattr(user, "is_superuser", False)
        or getattr(user, "is_staff", False)
    ):
        return queryset

    return queryset.filter(
        uploaded_by=user
    )


class RiskAnalysisUploadView(APIView):
    """
    POST /api/risk/upload/

    Kept under the existing route so no URL change is required, but this
    endpoint no longer receives an uploaded JSON file.

    Body:
        {
          "payload_manifest_id": 7,
          "force": false
        }

    The endpoint resolves the prepared dataset generated by Data Preparation,
    loads only the canonical combined V2 payload, validates it, derives the
    dashboard dynamically, and stores the deterministic result.

    It never loads payload_*_improved.json and never merges section-specific
    report-generation payloads.
    """

    permission_classes = [
        IsAuthenticated,
    ]

    def post(self, request):
        serializer = (
            StartRiskAnalysisSerializer(
                data=request.data,
                context={
                    "request": request,
                },
            )
        )
        serializer.is_valid(
            raise_exception=True
        )

        manifest = serializer.context[
            "payload_manifest"
        ]
        force = serializer.validated_data[
            "force"
        ]

        if not force:
            existing = (
                RiskAnalysis.objects
                .filter(
                    payload_manifest=manifest,
                    uploaded_by=request.user,
                    status=(
                        RiskAnalysis.STATUS_READY
                    ),
                )
                .order_by("-created_at")
                .first()
            )

            if existing is not None:
                return Response(
                    RiskAnalysisDetailSerializer(
                        existing
                    ).data,
                    status=status.HTTP_200_OK,
                )

        analysis = RiskAnalysis.objects.create(
            uploaded_by=request.user,
            payload_manifest=manifest,
            original_filename=(
                f"Prepared dataset "
                f"{manifest.version}"
            ),
            bank_id=manifest.bank.code,
            bank_name=manifest.bank.name,
            reporting_year=(
                manifest.reporting_year
            ),
            raw_payload={},
            status=(
                RiskAnalysis.STATUS_PENDING
            ),
        )

        try:
            payload_dir = (
                resolve_payload_directory(
                    manifest
                )
            )
            payload, source_filename = (
                services.load_canonical_payload(
                    payload_dir,
                    bank_code=(
                        manifest.bank.code
                    ),
                    bank_name=(
                        manifest.bank.name
                    ),
                    reporting_year=(
                        manifest.reporting_year
                    ),
                )
            )

            analysis.original_filename = (
                source_filename
            )

            logger.info(
                "Loaded canonical payload %s "
                "for risk analysis %s.",
                source_filename,
                analysis.id,
            )

            is_usable, warnings = (
                validators.validate_payload(
                    payload
                )
            )
            analysis.validation_warnings = (
                warnings
            )

            if not is_usable:
                analysis.status = (
                    RiskAnalysis.STATUS_FAILED
                )
                analysis.error_message = "; ".join(
                    warning["message"]
                    for warning in warnings
                    if (
                        warning.get("level")
                        == "error"
                    )
                )
                analysis.save(
                    update_fields=[
                        "validation_warnings",
                        "status",
                        "error_message",
                        "updated_at",
                    ]
                )

                return Response(
                    RiskAnalysisDetailSerializer(
                        analysis
                    ).data,
                    status=(
                        status.HTTP_422_UNPROCESSABLE_ENTITY
                    ),
                )

            analysis.processed = (
                services.process_payload(
                    payload
                )
            )
            analysis.status = (
                RiskAnalysis.STATUS_READY
            )
            analysis.error_message = ""
            analysis.save(
                update_fields=[
                    "original_filename",
                    "processed",
                    "validation_warnings",
                    "status",
                    "error_message",
                    "updated_at",
                ]
            )

            return Response(
                RiskAnalysisDetailSerializer(
                    analysis
                ).data,
                status=status.HTTP_201_CREATED,
            )

        except (
            PayloadStorageError,
            services.RiskPayloadError,
        ) as exc:
            logger.warning(
                "Prepared dataset could not be "
                "resolved for risk analysis %s: %s",
                analysis.id,
                exc,
            )
            analysis.status = (
                RiskAnalysis.STATUS_FAILED
            )
            analysis.error_message = str(exc)
            analysis.save(
                update_fields=[
                    "status",
                    "error_message",
                    "updated_at",
                ]
            )

            return Response(
                RiskAnalysisDetailSerializer(
                    analysis
                ).data,
                status=(
                    status.HTTP_422_UNPROCESSABLE_ENTITY
                ),
            )

        except Exception as exc:
            logger.exception(
                "Risk analysis processing failed "
                "for %s.",
                analysis.id,
            )
            analysis.status = (
                RiskAnalysis.STATUS_FAILED
            )
            analysis.error_message = (
                "Risk analysis could not be "
                "completed."
            )
            analysis.save(
                update_fields=[
                    "status",
                    "error_message",
                    "updated_at",
                ]
            )

            return Response(
                RiskAnalysisDetailSerializer(
                    analysis
                ).data,
                status=(
                    status.HTTP_500_INTERNAL_SERVER_ERROR
                ),
            )


class RiskAnalysisListView(
    generics.ListAPIView
):
    """
    GET /api/risk/analyses/

    Optional filters:
      payload_manifest_id
      bank_code
      reporting_year

    Administrators can see all analyses. Other users see analyses they
    created.
    """

    serializer_class = (
        RiskAnalysisListSerializer
    )
    permission_classes = [
        IsAuthenticated,
    ]

    def get_queryset(self):
        queryset = (
            _analysis_queryset_for_user(
                self.request.user
            )
        )

        manifest_id = (
            self.request.query_params.get(
                "payload_manifest_id"
            )
        )
        bank_code = (
            self.request.query_params.get(
                "bank_code"
            )
        )
        reporting_year = (
            self.request.query_params.get(
                "reporting_year"
            )
        )

        if manifest_id:
            queryset = queryset.filter(
                payload_manifest_id=(
                    manifest_id
                )
            )

        if bank_code:
            queryset = queryset.filter(
                bank_id__iexact=bank_code
            )

        if reporting_year:
            queryset = queryset.filter(
                reporting_year=reporting_year
            )

        return queryset


class RiskAnalysisDetailView(
    generics.RetrieveAPIView
):
    serializer_class = (
        RiskAnalysisDetailSerializer
    )
    permission_classes = [
        IsAuthenticated,
    ]
    lookup_field = "id"

    def get_queryset(self):
        return _analysis_queryset_for_user(
            self.request.user
        )


class AssessmentGenerateView(APIView):
    permission_classes = [
        IsAuthenticated,
    ]

    def post(self, request, id):
        analysis = (
            _analysis_queryset_for_user(
                request.user
            )
            .filter(id=id)
            .first()
        )

        if analysis is None:
            return Response(
                {
                    "detail": (
                        "Risk analysis not found."
                    )
                },
                status=(
                    status.HTTP_404_NOT_FOUND
                ),
            )

        if (
            analysis.status
            != RiskAnalysis.STATUS_READY
            or not analysis.processed
        ):
            return Response(
                {
                    "detail": (
                        "The risk analysis is not "
                        "ready."
                    )
                },
                status=(
                    status.HTTP_409_CONFLICT
                ),
            )

        result = llm.generate_assessment(
            analysis.processed
        )

        assessment_text = result[
            "assessment"
        ]
        cited_evidence = (
            llm.select_cited_evidence(
                assessment_text,
                analysis.processed.get(
                    "evidence",
                    [],
                ),
            )
        )

        record = (
            AssessmentResult.objects.create(
                analysis=analysis,
                assessment_text=(
                    assessment_text
                ),
                recommendations=(
                    result[
                        "recommendations"
                    ]
                ),
                avoid=result["avoid"],
                evidence=(
                    cited_evidence
                ),
                model_used=(
                    result["model_used"]
                ),
                is_fallback=(
                    result["is_fallback"]
                ),
            )
        )

        return Response(
            AssessmentResultSerializer(
                record
            ).data,
            status=status.HTTP_201_CREATED,
        )


class AssessmentLatestView(
    generics.RetrieveAPIView
):
    serializer_class = (
        AssessmentResultSerializer
    )
    permission_classes = [
        IsAuthenticated,
    ]

    def get_object(self):
        analysis_id = self.kwargs["id"]

        allowed_analysis = (
            _analysis_queryset_for_user(
                self.request.user
            )
            .filter(id=analysis_id)
            .values_list(
                "id",
                flat=True,
            )
            .first()
        )

        if allowed_analysis is None:
            raise Http404(
                "Risk analysis not found."
            )

        assessment = (
            AssessmentResult.objects
            .filter(
                analysis_id=analysis_id
            )
            .order_by("-created_at")
            .first()
        )

        if assessment is None:
            raise Http404(
                "No assessment has been "
                "generated yet."
            )

        return assessment
