# Generated by Django 6.0.6 on 2026-07-01 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
                ('minio_prefix', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('available', 'Available'), ('invalid', 'Invalid'), ('archived', 'Archived')], default='available', max_length=30)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bank__code', '-reporting_year', '-created_at'],
                'unique_together': {('bank', 'reporting_year', 'version')},
            },
        ),
    ]
