# Generated by Django 6.0.6 on 2026-07-01 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ifrs_assets', '0001_initial'),
        ('organizations', '0001_initial'),
        ('payloads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_year', models.IntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_warnings', 'Completed with warnings'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=40)),
                ('current_stage', models.CharField(default='queued', max_length=100)),
                ('progress_percent', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('langgraph_thread_id', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('final_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ifrs_asset_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ifrs_assets.ifrsassetbundle')),
                ('payload_manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payloads.payloadmanifest')),
                ('style_asset_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ifrs_assets.styleassetbundle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=100)),
                ('warning_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='report_generation.reportgenerationjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_year', models.IntegerField()),
                ('version_number', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_version', to='report_generation.reportgenerationjob')),
            ],
            options={
                'ordering': ['bank__code', '-reporting_year', '-version_number'],
                'unique_together': {('bank', 'reporting_year', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('validation_failed', 'Validation failed'), ('revised', 'Revised'), ('approved', 'Approved'), ('warning', 'Warning'), ('failed', 'Failed')], default='generated', max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('revision_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='report_generation.reportversion')),
            ],
            options={
                'ordering': ['section_key'],
                'unique_together': {('report_version', 'section_key')},
            },
        ),
    ]
