# Generated by Django 6.0.6 on 2026-07-01 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('payload', 'Payload'), ('evidence_map', 'Evidence map'), ('coverage', 'Coverage'), ('missing_requirements', 'Missing requirements'), ('disclosure_plan', 'Disclosure plan'), ('draft_section', 'Draft section'), ('claims_register', 'Claims register'), ('validation_result', 'Validation result'), ('approved_section', 'Approved section'), ('final_markdown', 'Final Markdown'), ('final_pdf', 'Final PDF'), ('warning_summary', 'Warning summary'), ('audit_summary', 'Audit summary'), ('log', 'Log'), ('error', 'Error')], max_length=80)),
                ('bucket', models.CharField(max_length=100)),
                ('object_key', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='report_generation.reportgenerationjob')),
                ('report_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='report_generation.reportversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
