# Generated by Django 6.0.6 on 2026-07-08 15:45

import data_preparation.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPreparationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_input_folder', models.CharField(blank=True, max_length=500)),
                ('patched_output_folder', models.CharField(blank=True, max_length=500)),
                ('payload_output_folder', models.CharField(blank=True, max_length=500)),
                ('log_output_folder', models.CharField(blank=True, max_length=500)),
                ('total_payloads_generated', models.PositiveIntegerField(default=0)),
                ('total_section_payloads_generated', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPreparationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('row_identifier', models.CharField(blank=True, max_length=255)),
                ('is_report_blocking', models.BooleanField(default=False)),
                ('is_internal_only', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='data_preparation.datapreparationjob')),
            ],
            options={
                'ordering': ['severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('validating', 'Validating'), ('ready', 'Ready'), ('failed', 'Failed')], default='created', max_length=30)),
                ('raw_folder', models.CharField(blank=True, max_length=500)),
                ('patched_folder', models.CharField(blank=True, max_length=500)),
                ('payload_folder', models.CharField(blank=True, max_length=500)),
                ('log_folder', models.CharField(blank=True, max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_files_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datapreparationjob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_jobs', to='data_preparation.datauploadbatch'),
        ),
        migrations.CreateModel(
            name='UploadedDataFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=data_preparation.models.uploaded_data_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('zip', 'ZIP'), ('other', 'Other')], default='other', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='data_preparation.datauploadbatch')),
            ],
            options={
                'ordering': ['original_filename'],
            },
        ),
        migrations.CreateModel(
            name='PreparedPayloadArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_id', models.CharField(max_length=50)),
                ('reporting_year', models.PositiveIntegerField(default=2024)),
                ('payload_type', models.CharField(choices=[('full', 'Full payload'), ('section', 'Section payload'), ('audit', 'Audit artifact')], default='full', max_length=30)),
                ('section_name', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=data_preparation.models.prepared_payload_file_path)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload_artifacts', to='data_preparation.datapreparationjob')),
            ],
            options={
                'ordering': ['bank_id', 'payload_type', 'section_name'],
                'indexes': [models.Index(fields=['bank_id', 'reporting_year'], name='data_prepar_bank_id_727e10_idx'), models.Index(fields=['payload_type'], name='data_prepar_payload_86cc15_idx')],
            },
        ),
    ]
